blueprint:
  name: Motion and Door Activated Light with Auto-Off
  description: >-
    Turns on a light when a specified door is opened or motion is detected.
    The light will then turn off after a configurable amount of time with no motion,
    but only if the door is also closed.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: The motion sensor that will trigger the light.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    door_sensor:
      name: Door Sensor
      description: The door sensor that will also trigger the light.
      selector:
        entity:
          domain: binary_sensor
          device_class: door
    target_light:
      name: Target Light
      description: The light, switch, or group to turn on and off.
      selector:
        target:
          entity:
            domain:
              - light
              - switch
    wait_time:
      name: No Motion Wait Time
      description: The time in minutes to wait before turning off the light after motion stops.
      default: 5
      selector:
        number:
          min: 0
          max: 120
          unit_of_measurement: minutes

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: 'on'
    id: 'motion_detected'
  - platform: state
    entity_id: !input door_sensor
    to: 'on'
    id: 'door_opened'
  - platform: state
    entity_id: !input motion_sensor
    to: 'off'
    for:
      minutes: !input wait_time
    id: 'no_motion'

action:
  - choose:
      # --- ACTION FOR TURNING THE LIGHT ON ---
      - conditions:
          - condition: trigger
            id:
              - 'motion_detected'
              - 'door_opened'
        sequence:
          - service: homeassistant.turn_on
            target: !input target_light

      # --- ACTION FOR TURNING THE LIGHT OFF ---
      - conditions:
          - condition: trigger
            id: 'no_motion'
          # Also check that the door is closed before turning off
          - condition: state
            entity_id: !input door_sensor
            state: 'off'
        sequence:
          - service: homeassistant.turn_off
            target: !input target_light
            
